apps/category/models.py
from apps import db
import datetime
from flask_authorize import PermissionsMixin


class Category(db.Model, PermissionsMixin):
    __tablename__ = 'categories'

    __permissions__ = dict(
        owner=['read', 'update', 'delete', 'revoke'],
        group=['read', 'update'],
        other=['read']
    )

    id = db.Column(db.Integer, primary_key=True)
    category_name = db.Column(db.String(64))
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow())
    updated_at = db.Column(db.DateTime, default=datetime.datetime.utcnow())
   

apps/category/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField
from wtforms.validators import DataRequired


class CreateCategoryForm(FlaskForm):
    category_name = StringField('category_name', id='category_name', validators=[DataRequired()])

apps/category/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'category_blueprint',
    __name__,
    url_prefix=''
)

apps/category/routes.py
from apps.category import blueprint
from flask import render_template, redirect, request, url_for, flash
from flask_login import login_required
from apps.category.models import Category
from apps.category.forms import CreateCategoryForm

from apps import db, authorize
from werkzeug.exceptions import Unauthorized


@blueprint.route('/category')
@login_required
@authorize.read
def index():
    category = Category.query.all()
    return render_template('category/index.html', category=category)


@blueprint.route('/category/create', methods=['GET', 'POST'])
@login_required
def create():
    if not authorize.create(Category):
        raise Unauthorized
    category_form = CreateCategoryForm(request.form)
    if 'create' in request.form:
        category_name = request.form['category_name']
        category = Category(
            category_name=category_name
        )
        db.session.add(category)
        db.session.commit()
        return redirect(url_for('category_blueprint.index'))
    return render_template('category/create.html', form=category_form)


@blueprint.route('/category/update/<int:category_id>', methods=['GET', 'POST'])
@authorize.update
@login_required
def update(category_id):
    category = Category.query.filter_by(id=category_id).first()
    category_form = CreateCategoryForm(formdata=request.form, obj=category)
    if not authorize.update(category):
        raise Unauthorized
    if 'update' in request.form:
        category_form.populate_obj(category)
        db.session.commit()
        return redirect(url_for('category_blueprint.index'))
    return render_template('category/edit.html', form=category_form)


@blueprint.route('/category/delete/<int:category_id>', methods=['GET', 'POST'])
@authorize.delete
@login_required
def delete(category_id):
    category = Category.query.filter_by(id=category_id).first()
    if not authorize.delete(category):
        raise Unauthorized
    if category:
        db.session.delete(category)
        db.session.commit()
        return redirect(url_for('category_blueprint.index'))
    return redirect(url_for('category_blueprint.index'))

apps/templates/category/create.html
{% extends "layouts/base.html" %}

{% block title %} Category {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">

            <div class="pcoded-content">
                <div class="pcoded-inner-content">
                    <!-- [ breadcrumb ] start -->

                    <!-- [ breadcrumb ] end -->
                    <div class="main-body">
                        <div class="page-wrapper">
                            <!-- [ Main Content ] start -->
                           <div class="row">
                                <div class="col-sm-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5>Create Category</h5>
                                        </div>
                                        <div class="card-body">

                                            <div class="row">
                                                <div class="col-md-6">
                                                    <form role="form" method="post">
                                                        {{ form.hidden_tag() }}
                                                        <div class="form-group">
                                                            <label for="unit_name">Category Name</label>
                                                            {{ form.category_name(placeholder="Enter Category Name", class="input form-control") }}
                                                        </div>
                                                        <button type="submit" name="create" class="btn btn-primary">Submit</button>
                                                    </form>
                                                </div>

                                            </div>


                                        </div>
                                    </div>

                                </div>
                            </div>
                            <!-- [ Main Content ] end -->
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/category/edit.html
{% extends "layouts/base.html" %}

{% block title %} Category {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">

            <div class="pcoded-content">
                <div class="pcoded-inner-content">
                    <!-- [ breadcrumb ] start -->

                    <!-- [ breadcrumb ] end -->
                    <div class="main-body">
                        <div class="page-wrapper">
                            <!-- [ Main Content ] start -->
                           <div class="row">
                                <div class="col-sm-12">
                                    <div class="card">
                                        <div class="card-header">

                                            <h5>Update Category</h5>
                                        </div>
                                        <div class="card-body">

                                            <div class="row">
                                                <div class="col-md-6">
                                                    <form role="form" method="post">
                                                        {{ form.hidden_tag() }}
                                                        <div class="form-group">
                                                            <label for="category_name">Category Name</label>
                                                            {{ form.category_name(placeholder="Enter Category Name", class="input form-control") }}
                                                        </div>
                                                        <button type="submit" name="update" class="btn btn-primary">Submit</button>
                                                    </form>
                                                </div>

                                            </div>


                                        </div>
                                    </div>

                                </div>
                            </div>
                            <!-- [ Main Content ] end -->
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/category/index.html
{% extends "layouts/base.html" %}
{% set active_page = "category" %}
{% block title %} Category {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">

            <div class="pcoded-content">
                <div class="pcoded-inner-content">
                    <!-- [ breadcrumb ] start -->

                    <!-- [ breadcrumb ] end -->
                    <div class="main-body">
                        <div class="page-wrapper">
                            <!-- [ Main Content ] start -->
                            <div class="row">
                                <div class="col-xl-12">
                                    <div class="card">
                                        <div class="card-header">

                                            <h5>Category Lists</h5>
                                            <a href="{{ url_for('category_blueprint.create') }}" type="button"
                                               class="btn btn-success float-right  mr-2">Add Category</a>

                                        </div>
                                        <div class="card-block table-border-style">
                                            <div class="table-responsive">
                                                <table class="table table-striped table-bordered nowrap dataTable">
                                                    <thead>
                                                    <tr>
                                                        <th>#</th>
                                                        <th>Category Name</th>
                                                        <th>Action</th>

                                                    </tr>
                                                    </thead>
                                                    <tbody>

                                                    {% for row in category %}
                                                        <tr>
                                                            <td>{{ loop.index }}</td>
                                                            <td>{{ row.category_name }}</td>
                                                            <td>
                                                                {% if authorize.update(row) %}
                                                                    <a class="btn btn-success text-white" href="{{ url_for('category_blueprint.update', category_id=row.id)}}">Edit</a>
                                                                {% endif %}
                                                                {% if authorize.delete(row) %}
                                                                    <a class="btn btn-danger text-white" href="{{ url_for('category_blueprint.delete', category_id=row.id)}}">Delete</a>
                                                                {% endif %}
                                                            </td>
                                                        </tr>

                                                    {% endfor %}

                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- [ Main Content ] end -->
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}