apps/roles/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, TextAreaField, HiddenField
from wtforms.validators import DataRequired


class CreateRoleForm(FlaskForm):
    name = StringField('name', id='name', validators=[DataRequired()])
    allowances = HiddenField('allowances', id='allowances')
    restrictions = StringField('restrictions', id='restrictions')

apps/roles/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'roles_blueprint',
    __name__,
    url_prefix=''
)

apps/roles/routes.py
import json, sys
from apps.roles import blueprint
from flask import render_template, redirect, request, url_for, flash, jsonify
from flask_login import login_required
from apps.authentication.models import Role
from apps.roles.forms import CreateRoleForm

from apps import db, authorize
from werkzeug.exceptions import Unauthorized, NotFound


@blueprint.route('/roles', methods=['GET'])
@login_required
def index():
    roles = Role.query.all()
    if not authorize.create(Role):
        raise Unauthorized
    return render_template('roles/index.html', roles=roles)


@blueprint.route('/roles/create', methods=['GET', 'POST'])
@login_required
def create():
    if not authorize.create(Role):
        raise Unauthorized
    role_form = CreateRoleForm(request.form)
    if 'create' in request.form:
        name = request.form['name']
        roles = Role(
            name=name
        )
        db.session.add(roles)
        db.session.commit()
        return redirect(url_for('roles_blueprint.index'))
    return render_template('roles/create.html', form=role_form)


@blueprint.route('/roles/update/<int:role_id>', methods=['GET', 'POST'])
@authorize.update
@login_required
def update(role_id):
    role = Role.query.filter_by(id=role_id).first()
    role_list = role.allowances

    role_form = CreateRoleForm(formdata=request.form, obj=role)
    if not authorize.update(role):
        raise Unauthorized
    if 'update' in request.form:
        role_name = request.form['name']
        allowances = request.form['allowances']

        json_object = json.loads(allowances)

        role.name = role_name
        role.allowances = json_object
        db.session.commit()

        return redirect(url_for('roles_blueprint.index'))
    return render_template('roles/edit.html', form=role_form, role=role, role_list=role_list)
#
#
# @blueprint.route('/brands/delete/<int:brand_id>', methods=['GET', 'POST'])
# @authorize.delete
# @login_required
# def delete(brand_id):
#     brand = Brands.query.filter_by(id=brand_id).first()
#     if not authorize.delete(brand):
#         raise Unauthorized
#     if brand:
#         db.session.delete(brand)
#         db.session.commit()
#         return redirect(url_for('brands_blueprint.index'))
#     return redirect(url_for('brands_blueprint.index'))

apps/templates/roles/create.html
{% extends "layouts/base.html" %}

{% block title %} Role {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">

            <div class="pcoded-content">
                <div class="pcoded-inner-content">
                    <!-- [ breadcrumb ] start -->

                    <!-- [ breadcrumb ] end -->
                    <div class="main-body">
                        <div class="page-wrapper">
                            <!-- [ Main Content ] start -->
                           <div class="row">
                                <div class="col-sm-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5>Create Role</h5>
                                        </div>
                                        <div class="card-body">

                                            <div class="row">
                                                <div class="col-md-6">
                                                    <form role="form" method="post">
                                                        {{ form.hidden_tag() }}
                                                        <div class="form-group">
                                                            <label for="role_name">Role Name</label>
                                                            {{ form.name(placeholder="Enter Role Name", class="input form-control") }}
                                                        </div>
                                                        <button type="submit" name="create" class="btn btn-primary">Submit</button>
                                                    </form>
                                                </div>

                                            </div>


                                        </div>
                                    </div>

                                </div>
                            </div>
                            <!-- [ Main Content ] end -->
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/roles/edit.html
{% extends "layouts/base.html" %}

{% block title %} Edit Role {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">

            <div class="pcoded-content">
                <div class="pcoded-inner-content">
                    <!-- [ breadcrumb ] start -->

                    <!-- [ breadcrumb ] end -->
                    <div class="main-body">
                        <div class="page-wrapper">
                            <!-- [ Main Content ] start -->
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="card">
                                        <div class="card-header">

                                            <h5>Update Role</h5>
                                        </div>
                                        <div class="card-body">

                                            <div class="row">
                                                <div class="col-md-6">
                                                    <form role="form" method="post">
                                                        {{ form.hidden_tag() }}
                                                        <div class="form-group">
                                                            <label for="role_name">Role Name</label>
                                                            {{ form.name(placeholder="Enter Role Name", class="input form-control") }}
                                                        </div>
                                                        <div class="form-group">

                                                            {{ form.allowances(placeholder="Enter Role Name", class="input form-control") }}
                                                        </div>
                                                        <hr class="m-20 p-10">

                                                        {% for key in role_list.keys() %}


                                                            <div class="row check_group">
                                                            <div class="col-md-4">
                                                                <h4>{{ key }}</h4>
                                                            </div>


                                                            <div class="col-md-6">

                                                                <div class="col-md-12">

                                                                    <div class="checkbox d-inline">
                                                            <input type="checkbox" name="{{ key }}_read" value="{{ key }}_read"
                                                                                id="{{ key }}_read"
                                                                    {% for a_value in role_list[key] %}
                                                            {% if a_value=="read" %} checked {% endif %} {% endfor %}>
                                                                        <label
                                                                                for="{{ key }}_read" class="cr"> View
                                                                            {{ key }}</label>
                                                                    </div>

                                                                </div>

                                                                <div class="col-md-12">
                                                                    <div class="checkbox d-inline">
                                                                        <input
                                                                                type="checkbox" name="{{ key }}_create" value="{{ key }}_create"
                                                                                id="{{ key }}_create" {% for a_value in role_list[key] %}
                                                            {% if a_value=="create" %} checked {% endif %} {% endfor %}>
                                                                        <label
                                                                                for="{{ key }}_create" class="cr"> Add
                                                                            {{ key }}</label>
                                                                    </div>
                                                                </div>

                                                                <div class="col-md-12">
                                                                    <div class="checkbox d-inline">
                                                                        <input
                                                                                type="checkbox" name="{{ key }}_update" value="{{ key }}_update"
                                                                                id="{{ key }}_update" {% for a_value in role_list[key] %}
                                                            {% if a_value=="update" %} checked {% endif %} {% endfor %}>
                                                                        <label
                                                                                for="{{ key }}_update" class="cr"> Edit
                                                                            {{ key }}</label>
                                                                    </div>
                                                                </div>

                                                                <div class="col-md-12">
                                                                    <div class="checkbox d-inline">
                                                                        <input
                                                                                type="checkbox" name="{{ key }}_delete" value="{{ key }}_delete"
                                                                                id="{{ key }}_delete" {% for a_value in role_list[key] %}
                                                            {% if a_value=="delete" %} checked {% endif %} {% endfor %}>
                                                                        <label
                                                                                for="{{ key }}_delete" class="cr"> Delete
                                                                            {{ key }}</label>
                                                                    </div>
                                                                </div>

                                                            </div>

                                                        </div>

{% endfor %}

                                                        <button type="submit" name="update" class="btn btn-primary">
                                                            Submit
                                                        </button>
                                                    </form>
                                                </div>

                                            </div>


                                        </div>
                                    </div>

                                </div>
                            </div>
                            <!-- [ Main Content ] end -->
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js"></script>
    <script type="application/javascript">
        let data = document.getElementById("allowances").value
        let allow_data = data.replace(/'/g, '"');
        document.getElementById("allowances").value = allow_data;
    $(document).ready(function(){


        $('input[type="checkbox"]').click(function(){

            if($(this).is(":checked")){
                    console.log("Checkbox is checked.");

                    let check_value = $(this).val()
                    let key_value = check_value.split("_");
                    let key_a = key_value.slice(0, -1).join(' ')
                    let value_a = key_value.slice(-1).join(' ');

                    let allowances = document.getElementById("allowances").value;
                    let allowances_json = JSON.parse(allowances);
                    allowances_json[key_a].push(value_a);
                    let a_data = JSON.stringify(allowances_json);

                    document.getElementById("allowances").value = a_data;
                }
                else if($(this).is(":not(:checked)")){
                    let check_value = $(this).val()
                    let key_value = check_value.split("_");
                    let key_a = key_value.slice(0, -1).join(' ')
                    let value_a = key_value.slice(-1).join(' ');

                    let allowances = document.getElementById("allowances").value;
                    let allowances_json = JSON.parse(allowances);

                    _.remove(allowances_json[key_a], function(i){
                        return i == value_a;
                    })
                    let a_data = JSON.stringify(allowances_json);
                    document.getElementById("allowances").value = a_data;
                }
            });
    });


    </script>
{% endblock javascripts %}

apps/templates/roles/index.html
{% extends "layouts/base.html" %}
{% set active_page = "units" %}
{% block title %} Role {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">

            <div class="pcoded-content">
                <div class="pcoded-inner-content">
                    <!-- [ breadcrumb ] start -->

                    <!-- [ breadcrumb ] end -->
                    <div class="main-body">
                        <div class="page-wrapper">
                            <!-- [ Main Content ] start -->
                            <div class="row">
                                <div class="col-xl-12">
                                    <div class="card">
                                        <div class="card-header">

                                            <h5>Role Lists</h5>
                                        <span class="mb-2 text-muted">
                                            {% if msg %}
                                                <span class="text-danger">{{ msg | safe }}</span>
                                            {% endif %}
                                        </span>
                                            <a href="{{ url_for('roles_blueprint.create') }}" type="button"
                                               class="btn btn-success float-right  mr-2">Add Role</a>

                                        </div>
                                        <div class="card-block table-border-style">
                                            <div class="table-responsive">
                                                <table class="table table-striped table-bordered nowrap dataTable">
                                                    <thead>
                                                    <tr>
                                                        <th>#</th>
                                                        <th>Name</th>
                                                        <th>Action</th>

                                                    </tr>
                                                    </thead>
                                                    <tbody>

                                                    {% for row in roles %}
                                                        <tr>
                                                            <td>{{ loop.index }}</td>
                                                            <td>{{ row.name }}</td>
                                                            <td>
                                                                    <a class="btn btn-success text-white" href="{{ url_for('roles_blueprint.update', role_id=row.id)}}">Edit</a>
{#                                                                    <a class="btn btn-danger text-white" href="{{ url_for('units_blueprint.delete', user_id=row.id)}}">Delete</a>#}
                                                            </td>
                                                        </tr>

                                                    {% endfor %}

                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- [ Main Content ] end -->
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}