apps/brands/models.py
from apps import db
import datetime
from flask_authorize import PermissionsMixin


class Brands(db.Model, PermissionsMixin):
    __tablename__ = 'brands'

    __permissions__ = dict(
        owner=['read', 'update', 'delete', 'revoke'],
        group=['read', 'update'],
        other=['read']
    )

    id = db.Column(db.Integer, primary_key=True)
    brand_name = db.Column(db.String(64))
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow())
    updated_at = db.Column(db.DateTime, default=datetime.datetime.utcnow())

apps/brands/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField
from wtforms.validators import DataRequired


class CreateBrandForm(FlaskForm):
    brand_name = StringField('brand_name', id='brand_name', validators=[DataRequired()])

apps/brands/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'brands_blueprint',
    __name__,
    url_prefix=''
)

apps/brands/routes.py
from apps.brands import blueprint
from flask import render_template, redirect, request, url_for, flash
from flask_login import login_required
from apps.brands.models import Brands
from apps.brands.forms import CreateBrandForm

from apps import db, authorize
from werkzeug.exceptions import Unauthorized, NotFound


@blueprint.route('/brands', methods=['GET'])
@authorize.read
@login_required
def index():
    brands = Brands.query.all()
    return render_template('brands/index.html', brands=brands)


@blueprint.route('/brands/create', methods=['GET', 'POST'])
@login_required
def create():
    if not authorize.create(Brands):
        raise Unauthorized
    brand_form = CreateBrandForm(request.form)
    if 'create' in request.form:
        brand_name = request.form['brand_name']
        brands = Brands(
            brand_name=brand_name
        )
        db.session.add(brands)
        db.session.commit()
        return redirect(url_for('brands_blueprint.index'))
    return render_template('brands/create.html', form=brand_form)


@blueprint.route('/brands/update/<int:brand_id>', methods=['GET', 'POST'])
@authorize.update
@login_required
def update(brand_id):
    brand = Brands.query.filter_by(id=brand_id).first()
    brand_form = CreateBrandForm(formdata=request.form, obj=brand)
    if not authorize.update(brand):
        raise Unauthorized
    if 'update' in request.form:
        brand_form.populate_obj(brand)
        db.session.commit()
        return redirect(url_for('brands_blueprint.index'))
    return render_template('brands/edit.html', form=brand_form)


@blueprint.route('/brands/delete/<int:brand_id>', methods=['GET', 'POST'])
@authorize.delete
@login_required
def delete(brand_id):
    brand = Brands.query.filter_by(id=brand_id).first()
    if not authorize.delete(brand):
        raise Unauthorized
    if brand:
        db.session.delete(brand)
        db.session.commit()
        return redirect(url_for('brands_blueprint.index'))
    return redirect(url_for('brands_blueprint.index'))

apps/templates/brands/create.html
{% extends "layouts/base.html" %}

{% block title %} Brands {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">

            <div class="pcoded-content">
                <div class="pcoded-inner-content">
                    <!-- [ breadcrumb ] start -->

                    <!-- [ breadcrumb ] end -->
                    <div class="main-body">
                        <div class="page-wrapper">
                            <!-- [ Main Content ] start -->
                           <div class="row">
                                <div class="col-sm-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5>Create Brands</h5>
                                        </div>
                                        <div class="card-body">

                                            <div class="row">
                                                <div class="col-md-6">
                                                    <form role="form" method="post">
                                                        {{ form.hidden_tag() }}
                                                        <div class="form-group">
                                                            <label for="unit_name">Brands Name</label>
                                                            {{ form.brand_name(placeholder="Enter Brands Name", class="input form-control") }}
                                                        </div>
                                                        <button type="submit" name="create" class="btn btn-primary">Submit</button>
                                                    </form>
                                                </div>

                                            </div>


                                        </div>
                                    </div>

                                </div>
                            </div>
                            <!-- [ Main Content ] end -->
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/brands/edit.html
{% extends "layouts/base.html" %}

{% block title %} Brands {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">

            <div class="pcoded-content">
                <div class="pcoded-inner-content">
                    <!-- [ breadcrumb ] start -->

                    <!-- [ breadcrumb ] end -->
                    <div class="main-body">
                        <div class="page-wrapper">
                            <!-- [ Main Content ] start -->
                           <div class="row">
                                <div class="col-sm-12">
                                    <div class="card">
                                        <div class="card-header">

                                            <h5>Update Brand</h5>
                                        </div>
                                        <div class="card-body">

                                            <div class="row">
                                                <div class="col-md-6">
                                                    <form role="form" method="post">
                                                        {{ form.hidden_tag() }}
                                                        <div class="form-group">
                                                            <label for="brand_name">Brand Name</label>
                                                            {{ form.brand_name(placeholder="Enter Brand Name", class="input form-control") }}
                                                        </div>
                                                        <button type="submit" name="update" class="btn btn-primary">Submit</button>
                                                    </form>
                                                </div>

                                            </div>


                                        </div>
                                    </div>

                                </div>
                            </div>
                            <!-- [ Main Content ] end -->
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/brands/index.html
{% extends "layouts/base.html" %}
{% set active_page = "brands" %}
{% block title %} Brands {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">

            <div class="pcoded-content">
                <div class="pcoded-inner-content">
                    <!-- [ breadcrumb ] start -->

                    <!-- [ breadcrumb ] end -->
                    <div class="main-body">
                        <div class="page-wrapper">
                            <!-- [ Main Content ] start -->
                            <div class="row">
                                <div class="col-xl-12">
                                    <div class="card">
                                        <div class="card-header">

                                            <h5>Brands Lists</h5>
                                            <a href="{{ url_for('brands_blueprint.create') }}" type="button"
                                               class="btn btn-success float-right  mr-2">Add Brand</a>

                                        </div>
                                        <div class="card-block table-border-style">
                                            <div class="table-responsive">
                                                <table class="table table-striped table-bordered nowrap dataTable">
                                                    <thead>
                                                    <tr>
                                                        <th>#</th>
                                                        <th>Brand Name</th>
                                                        <th>Action</th>

                                                    </tr>
                                                    </thead>
                                                    <tbody>

                                                    {% for row in brands %}
                                                        <tr>
                                                            <td>{{ loop.index }}</td>
                                                            <td>{{ row.brand_name }}</td>
                                                            <td>

                                                                    <a class="btn btn-success text-white" href="{{ url_for('brands_blueprint.update', brand_id=row.id)}}">Edit</a>


                                                                    <a class="btn btn-danger text-white" href="{{ url_for('brands_blueprint.delete', brand_id=row.id)}}">Delete</a>

                                                            </td>
                                                        </tr>

                                                    {% endfor %}

                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- [ Main Content ] end -->
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}