apps/units/models.py
from apps import db
import datetime
from flask_authorize import PermissionsMixin


class Units(db.Model, PermissionsMixin):
    __tablename__ = 'units'

    __permissions__ = dict(
        owner=['read', 'update', 'delete', 'revoke'],
        group=['read', 'update'],
        other=['read']
    )

    id = db.Column(db.Integer, primary_key=True)
    unit_name = db.Column(db.String(64))
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow())
    updated_at = db.Column(db.DateTime, default=datetime.datetime.utcnow())

apps/units/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField
from wtforms.validators import DataRequired


class CreateUnitForm(FlaskForm):
    unit_name = StringField('unit_name', id='unit_name', validators=[DataRequired()])

apps/units/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'units_blueprint',
    __name__,
    url_prefix=''
)

apps/units/routes.py
from apps.units import blueprint
from flask import render_template, redirect, request, url_for, flash
from flask_login import login_required
from apps.units.models import Units
from apps.units.forms import CreateUnitForm

from apps import db, authorize
from werkzeug.exceptions import Unauthorized


@blueprint.route('/units')
@login_required
@authorize.read
def index():
    units = Units.query.all()
    print(units)
    return render_template('units/index.html', units=units)


@blueprint.route('/units/create', methods=['GET', 'POST'])
@login_required
@authorize.create(Units)
def create():
    unit_form = CreateUnitForm(request.form)
    if 'create' in request.form:
        unit_name = request.form['unit_name']
        units = Units(
            unit_name=unit_name
        )
        db.session.add(units)
        db.session.commit()
        return redirect(url_for('units_blueprint.index'))
    return render_template('units/create.html', form=unit_form)


@blueprint.route('/units/update/<int:unit_id>', methods=['GET', 'POST'])
@login_required
def update(unit_id):
    unit = Units.query.filter_by(id=unit_id).first()
    unit_form = CreateUnitForm(formdata=request.form, obj=unit)
    if not authorize.update(unit):
        raise Unauthorized
    if 'update' in request.form:
        unit_form.populate_obj(unit)
        db.session.commit()
        return redirect(url_for('units_blueprint.index'))
    return render_template('units/edit.html', form=unit_form)


@blueprint.route('/units/delete/<int:unit_id>', methods=['GET', 'POST'])
@login_required
def delete(unit_id):
    unit = Units.query.filter_by(id=unit_id).first()
    if not authorize.delete(unit):
        raise Unauthorized
    if unit:
        db.session.delete(unit)
        db.session.commit()
        return redirect(url_for('units_blueprint.index'))
    return redirect(url_for('units_blueprint.index'))

apps/templates/units/create.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">

            <div class="pcoded-content">
                <div class="pcoded-inner-content">
                    <!-- [ breadcrumb ] start -->

                    <!-- [ breadcrumb ] end -->
                    <div class="main-body">
                        <div class="page-wrapper">
                            <!-- [ Main Content ] start -->
                           <div class="row">
                                <div class="col-sm-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5>Create Unit</h5>
                                        </div>
                                        <div class="card-body">

                                            <div class="row">
                                                <div class="col-md-6">
                                                    <form role="form" method="post">
                                                        {{ form.hidden_tag() }}
                                                        <div class="form-group">
                                                            <label for="unit_name">Unit Name</label>
                                                            {{ form.unit_name(placeholder="Enter Unit Name", class="input form-control") }}
                                                        </div>
                                                        <button type="submit" name="create" class="btn btn-primary">Submit</button>
                                                    </form>
                                                </div>

                                            </div>


                                        </div>
                                    </div>

                                </div>
                            </div>
                            <!-- [ Main Content ] end -->
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/units/edit.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">

            <div class="pcoded-content">
                <div class="pcoded-inner-content">
                    <!-- [ breadcrumb ] start -->

                    <!-- [ breadcrumb ] end -->
                    <div class="main-body">
                        <div class="page-wrapper">
                            <!-- [ Main Content ] start -->
                           <div class="row">
                                <div class="col-sm-12">
                                    <div class="card">
                                        <div class="card-header">

                                            <h5>Update Unit</h5>
                                        </div>
                                        <div class="card-body">

                                            <div class="row">
                                                <div class="col-md-6">
                                                    <form role="form" method="post">
                                                        {{ form.hidden_tag() }}
                                                        <div class="form-group">
                                                            <label for="unit_name">Unit Name</label>
                                                            {{ form.unit_name(placeholder="Enter Unit Name", class="input form-control") }}
                                                        </div>
                                                        <button type="submit" name="update" class="btn btn-primary">Submit</button>
                                                    </form>
                                                </div>

                                            </div>


                                        </div>
                                    </div>

                                </div>
                            </div>
                            <!-- [ Main Content ] end -->
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/units/index.html
{% extends "layouts/base.html" %}
{% set active_page = "units" %}
{% block title %} Dashboard {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">

            <div class="pcoded-content">
                <div class="pcoded-inner-content">
                    <!-- [ breadcrumb ] start -->

                    <!-- [ breadcrumb ] end -->
                    <div class="main-body">
                        <div class="page-wrapper">
                            <!-- [ Main Content ] start -->
                            <div class="row">
                                <div class="col-xl-12">
                                    <div class="card">
                                        <div class="card-header">

                                            <h5>Unit Lists</h5>
                                            <a href="{{ url_for('units_blueprint.create') }}" type="button"
                                               class="btn btn-success float-right  mr-2">Add Unit</a>

                                        </div>
                                        <div class="card-block table-border-style">
                                            <div class="table-responsive">
                                                <table class="table table-striped table-bordered nowrap dataTable">
                                                    <thead>
                                                    <tr>
                                                        <th>#</th>
                                                        <th>Unit Name</th>
                                                        <th>Action</th>

                                                    </tr>
                                                    </thead>
                                                    <tbody>

                                                    {% for row in units %}
                                                        <tr>
                                                            <td>{{ loop.index }}</td>
                                                            <td>{{ row.unit_name }}</td>
                                                            <td>
                                                                {% if authorize.update(row) %}
                                                                    <a class="btn btn-success text-white" href="{{ url_for('units_blueprint.update', unit_id=row.id)}}">Edit</a>
                                                                {% endif %}
                                                                {% if authorize.delete(row) %}
                                                                    <a class="btn btn-danger text-white" href="{{ url_for('units_blueprint.delete', unit_id=row.id)}}">Delete</a>
                                                                {% endif %}
                                                            </td>
                                                        </tr>

                                                    {% endfor %}

                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- [ Main Content ] end -->
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}